### ISSUE TITLE
Add Hotkeys

### ISSUE THREAD

**Issue by shailpatels** [Bram-Hub/VisualLogic#11]
It would be nice if there were hotkeys to quickly do an action.
Things that could be hotkeyed:

- [x] create variable (this should be done at the position of the cursor and associate to the key pressed)
- [x] create a cut (also at cursor)
- [x] open up options menu
- [x] turn on delete mode
- [x] turn on copy mode

In the future this should be configurable, but static should do for now?
I think creating a config.json file to load all of these values would make sense and 
then read them whenever needed from it.
others?

**Comment by sezenack** [comment]
added the hotkeys
